version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: kk_products_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongodata:/data/db

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    container_name: kk_products_service
    ports:
      - '8081:8081'
